version: '3.1'

services:
    web:
        image: lsapan/docker-swarm-demo-web
        command: gunicorn --bind 0.0.0.0:5000 wsgi:app
        deploy:
            mode: replicated
            replicas: 2
            # placement:
            #     constraints:
            #         - node.label.api == true
        secrets:
            - db_password

    nginx:
        image: lsapan/docker-swarm-demo-nginx
        ports:
            - 8000:80
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.label.demo_nginx == true

    redis:
        image: redis
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]

secrets:
    db_password:
        external: true
